Convert Affymetrix.Rnw to Affymetrix.Rmd
smgogarten/GWASTools pull request #14
Opened 2023-06-15 15:29 UTC by sonali8434

@smgogarten kindly review this PR. We use this [Review PR](https://bioconductor.github.io/sweave2rmd/articles/contribute.html#review-a-pull-request) section of our document to review it. If you want us to make any changes in .Rmd file then please let us know. Any suggestions would be appreciated.

After you merge the PR, remember to bump the version in the DESCRIPTION file so that the Bioconductor build system will recognize the new changes and [push the changes to Bioconductor's git repository](https://contributions.bioconductor.org/git-version-control.html#push-to-github-bioc).

Original [PDF](https://bioconductor.org/packages/release/bioc/vignettes/GWASTools/inst/doc/Affymetrix.pdf)
Converted [HTML](https://rpubs.com/Sonali8434/1054966)

2023-06-20 22:07 UTC, smgogarten requested changes
I noted one change about the author/affiliation split, otherwise this looks great. Thank you!

2023-06-20 22:07 UTC, smgogarten commented on vignettes/Affymetrix.Rmd
> +  - name: "GENEVA"
Please change to:
name: "GENEVA Coordinating Center"
affiliation: "Department of Biostatistics, University of Washington"

2023-06-21 17:10 UTC, sonali8434 commented
Hello @smgogarten, I have made the suggested changes.

 I want to inform you about one more thing, and I apologize for not mentioning it earlier. Generally, we give credits to the converter for converting Sweave documents. We ask maintainers if they want us to add ourselves as contributors in the description file and the .Rmd file. I wanted to ask if you would like me to add myself as a contributor for this conversion. It's totally fine to say no.

 Thank you so much for your time.

2023-06-22 00:41 UTC, smgogarten approved these changes

2023-06-22 00:42 UTC, smgogarten commented
Yes, go ahead and add yourself as a contributor. Thanks!

2023-06-22 07:20 UTC, sonali8434 commented
Thanks you! 

After you merge the PR, remember to bump the version in the DESCRIPTION file so that the Bioconductor build system will recognize the new changes and [push the changes to Bioconductor's git repository](https://contributions.bioconductor.org/git-version-control.html#push-to-github-bioc).

2023-06-22 12:34 UTC, merged